# Greykite example

In [38]:
import pandas as pd
from collections import defaultdict
import warnings
warnings.filterwarnings("ignore")
import plotly
import itertools
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.dates import (
    MonthLocator,
    num2date,
    AutoDateLocator,
    AutoDateFormatter,
)
from matplotlib.ticker import FuncFormatter
from datetime import datetime
from pandas_datareader.data import DataReader

In [15]:
#!pip install greykite

In [16]:
 from greykite.common.data_loader import DataLoader
 from greykite.framework.templates.autogen.forecast_config import ForecastConfig
 from greykite.framework.templates.autogen.forecast_config import MetadataParam
 from greykite.framework.templates.forecaster import Forecaster
 from greykite.framework.templates.model_templates import ModelTemplateEnum
 from greykite.framework.utils.result_summary import summarize_grid_search_results

## Helpers

In [17]:
def subtract_one_month(timestamp):
    import datetime
    return( timestamp - datetime.timedelta(days=30) )

In [18]:
def subtract_one_year(timestamp):
    import datetime
    return( timestamp - datetime.timedelta(days=365) )

## CHF/DKK

In [19]:
item = 'CHFDKK=X'

In [20]:
# Get Data
data = DataReader(item,  "yahoo", datetime(1900,1,1), datetime.now())
data = pd.DataFrame(data)
data.index.name = 'ds'
data.reset_index(inplace=True)
data = data.dropna()
data = data.rename(columns={'Close' : 'y'})

INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [21]:
data

             ds     High       Low     Open        y  Volume  Adj Close
0    2003-12-01  4.79410  4.773700  4.79160  4.77920     0.0    4.77920
1    2003-12-02  4.78130  4.766700  4.78060  4.77050     0.0    4.77050
2    2003-12-03  4.77280  4.759600  4.77030  4.76550     0.0    4.76550
3    2003-12-04  4.77280  4.759400  4.76510  4.77050     0.0    4.77050
4    2003-12-05  4.78970  4.763900  4.77100  4.78700     0.0    4.78700
...         ...      ...       ...      ...      ...     ...        ...
4516 2021-05-27  6.80150  6.777100  6.79700  6.79800     0.0    6.79800
4517 2021-05-30  6.78250  6.743252  6.77630  6.77660     0.0    6.77660
4518 2021-05-31  6.78450  6.741725  6.76670  6.76650     0.0    6.76650
4519 2021-06-01  6.78840  6.746843  6.78410  6.78380     0.0    6.78380
4520 2021-06-03  6.78565  6.774200  6.77798  6.78411     0.0    6.78411

[4521 rows x 7 columns]

## Greykite Pipeline

In [22]:
 # specify dataset information
 metadata = MetadataParam(
     time_col="ds",  # name of the time column ("date" in example above)
     value_col="y",  # name of the value column ("sessions" in example above)
     freq="D"  # "H" for hourly, "D" for daily, "W" for weekly, etc.
               # Any format accepted by `pandas.date_range`
 )

In [24]:
 forecaster = Forecaster()  # Creates forecasts and stores the result
 result = forecaster.run_forecast_config(  # result is also stored as `forecaster.forecast_result`.
     df=data,
     config=ForecastConfig(
         model_template=ModelTemplateEnum.SILVERKITE.name,
         forecast_horizon=365,  # forecasts 365 steps ahead
         coverage=0.95,         # 95% prediction intervals
         metadata_param=metadata
     )
 )

te-packages/greykite/common/evaluation.py:90: UserWarning:

104 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.08% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1541 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.97% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

124 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.04% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1645 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.34% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.30% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1769 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1769 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

105 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

105 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 29.30% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/sklearn/transform/null_transformer.py:177: RuntimeWarning:

Input data has many null values. Missing 33.12% of one input.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1874 value(s) in y_true were NA or infinite and are omitted in error calc.

/home/oem/anaconda3/lib/python3.8/site-packages/greykite/common/evaluation.py:90: UserWarning:

1874 value(s) in y_true were NA or infinite and are omitted in error calc.

## Cross-validation

In [29]:
 grid_search = result.grid_search
 cv_results = summarize_grid_search_results(
     grid_search=grid_search,
     decimals=2,
     # The below saves space in the printed output. Remove to show all available metrics and columns.
     cv_report_metrics=None,
     column_order=["rank", "mean_test", "split_test", "mean_train", "split_train", "mean_fit_time", "mean_score_time", "params"])
 # Transposes to save space in the printed output
 cv_results["params"] = cv_results["params"].astype(str)
 cv_results.set_index("params", drop=True, inplace=True)
 cv_results.transpose()

params                              []
rank_test_MAPE                       1
mean_test_MAPE                    53.3
split_test_MAPE   (3.31, 92.61, 63.98)
mean_train_MAPE                  43.64
split_train_MAPE  (0.58, 66.51, 63.81)
mean_fit_time                    17.41
mean_score_time                   0.65

### Backtest

In [35]:
 backtest = result.backtest
 fig = backtest.plot()

ModuleNotFoundError: No module named 'plotly.validator_cache'

### Metrics

In [39]:
 backtest_eval = defaultdict(list)
 for metric, value in backtest.train_evaluation.items():
     backtest_eval[metric].append(value)
     backtest_eval[metric].append(backtest.test_evaluation[metric])
 metrics = pd.DataFrame(backtest_eval, index=["train", "test"]).T
 metrics

                                                         train       test
CORR                                                 0.0943161  0.0197351
R2                                                  0.00837261   -6093.54
MSE                                                    1540.71    41.3167
RMSE                                                   39.2519    6.42781
MAE                                                     5.8966    4.05514
MedAE                                                  2.79471     1.3303
MAPE                                                   60.4476    59.0632
MedAPE                                                 58.1005    19.3426
sMAPE                                                  21.0172    18.0092
Q80                                                    2.73882    1.01777
Q95                                                    2.63407    0.51287
Q99                                                    2.60614    0.37823
OutsideTolerance1p                                    0.985215   0.973077
OutsideTolerance2p                                    0.967144   0.942308
OutsideTolerance3p                                    0.952359   0.896154
OutsideTolerance4p                                    0.937808   0.846154
OutsideTolerance5p                                    0.923257   0.776923
Outside Tolerance (fraction)                              None       None
R2_null_model_score                                       None       None
Prediction Band Width (%)                               1704.8     1418.4
Prediction Band Coverage (fraction)                    0.83173          1
Coverage: Lower Band                                  0.743487   0.615385
Coverage: Upper Band                                 0.0882422   0.384615
Coverage Diff: Actual_Coverage - Intended_Coverage    -0.11827       0.05

In [42]:
result.model[-1].summary()

================================ Model Summary =================================

Number of observations: 6395,   Number of features: 122
Method: Ridge regression
Number of nonzero features: 122
Regularization parameter: 1.000e+05

Residuals:
         Min           1Q       Median           3Q          Max
      -11.43        -4.93       -3.152       -1.002        606.8

             Pred_col    Estimate   Std. Err Pr(>)_boot sig. code                     95%CI
            Intercept       8.135     0.4967     <2e-16       ***            (7.199, 9.115)
  events_C...New Year    0.003312   0.003909      0.652               (-0.0009369, 0.01136)
  events_C...w Year-1    0.001382   0.001894      0.620              (-0.0008738, 0.005447)
  events_C...w Year-2  -0.0004814  0.0001639      0.004        **    (-0.00085, -0.0002245)
  events_C...w Year+1    0.005263   0.006201      0.602               (-0.0009718, 0.02275)
  events_C...w Year+2  -0.0008054  0.0002687      0.008        **   (-0.001409, -0.0003676)
 events_Christmas Day  -0.0006062  0.0002083      0.010         *   (-0.001051, -0.0002344)
  events_C...as Day-1    0.005446   0.005825      0.626               (-0.0008644, 0.01773)
  events_C...as Day-2    0.003383   0.004181      0.640               (-0.0008996, 0.01164)
  events_C...as Day+1  -0.0006136   0.000198      0.006        **   (-0.001066, -0.0002757)
  events_C...as Day+2  -0.0006656  0.0002375      0.008        **    (-0.00121, -0.0003072)
  events_E...Ireland]   -0.001131  0.0003994      0.008        **   (-0.002037, -0.0004727)
  events_E...eland]-1   -0.001311  0.0004206      0.004        **    (-0.002336, -0.000654)
  events_E...eland]-2  -0.0007515  0.0002286      0.002        **    (-0.00123, -0.0003391)
  events_E...eland]+1  -0.0002775   0.000101      0.012         *  (-0.0005006, -0.0001031)
  events_E...eland]+2  -0.0001364  8.028e-05      0.092         .   (-0.0003119, 8.514e-06)
   events_Good Friday  -0.0003057  0.0001086      0.004        **  (-0.0005332, -0.0001078)
 events_Good Friday-1  -0.0002333  8.674e-05      0.006        **  (-0.0004125, -8.705e-05)
 events_Good Friday-2  -0.0001409  8.539e-05      0.092         .    (-0.000333, 4.512e-06)
 events_Good Friday+1  -0.0007515  0.0002286      0.002        **    (-0.00123, -0.0003391)
 events_Good Friday+2   -0.001311  0.0004206      0.004        **    (-0.002336, -0.000654)
  events_I...ence Day   -0.001048  0.0002536     <2e-16       ***    (-0.00161, -0.0006194)
  events_I...ce Day-1   -0.001039  0.0002719      0.002        **   (-0.001613, -0.0005954)
  events_I...ce Day-2   -0.001165  0.0003092      0.002        **   (-0.001843, -0.0006585)
  events_I...ce Day+1   -0.001142  0.0003182      0.004        **    (-0.001869, -0.000631)
  events_I...ce Day+2   0.0008133   0.001908      0.610               (-0.001674, 0.005072)
     events_Labor Day   -0.001608  0.0004585      0.004        **   (-0.002613, -0.0008898)
   events_Labor Day-1   -0.001787  0.0004737      0.006        **   (-0.002805, -0.0009881)
   events_Labor Day-2   -0.001288  0.0003054      0.002        **   (-0.001923, -0.0007069)
   events_Labor Day+1  -0.0008859  0.0002654      0.006        **   (-0.001475, -0.0004583)
   events_Labor Day+2  -0.0007897  0.0002469      0.004        **   (-0.001284, -0.0003665)
  events_Memorial Day   -0.001142   0.000388      0.008        **   (-0.002051, -0.0005529)
  events_M...al Day-1   -0.001325   0.000423      0.008        **   (-0.002269, -0.0006371)
  events_M...al Day-2  -0.0007562  0.0002352      0.008        **   (-0.001289, -0.0003632)
  events_M...al Day+1  -0.0002756  0.0001038      0.010         *  (-0.0004887, -9.497e-05)
  events_M...al Day+2  -0.0001296  8.192e-05      0.108             (-0.0002926, 3.109e-05)
 events_New Years Day  -0.0006128  0.0002119      0.006        **   (-0.001065, -0.0002757)
  events_N...rs Day-1    0.005435   0.006072      0.606               (-0.0008377, 0.01782)
  events_N...rs Day-2    0.003365   0.003879      0.624               (-0.0009838, 0.01148)
  events_N...rs Day+1  -0.0006119  0.0002111      0.012         *   (-0.001089, -0.0002636)
  events_N...rs Day+2  -0.0006533  0.0002235      0.010         *   (-0.001112, -0.0002818)
         events_Other    0.009402    0.01323      0.492                 (-0.01311, 0.03636)
       events_Other-1     0.02152    0.01407      0.120                (-0.004976, 0.05211)
       events_Other-2     0.02165    0.01298      0.098         .      (-0.002158, 0.04958)
       events_Other+1  -0.0007562   0.009655      0.930                 (-0.01651, 0.02046)
       events_Other+2    0.003367    0.01013      0.686                 (-0.01322, 0.02863)
  events_Thanksgiving  -0.0002585  9.966e-05      0.016         *  (-0.0004835, -9.469e-05)
  events_T...giving-1  -0.0001654  8.458e-05      0.054         .  (-0.0003453, -1.324e-05)
  events_T...giving-2     -0.0003  0.0001115      0.010         *  (-0.0005512, -0.0001168)
  events_T...giving+1  -0.0003293  0.0001145      0.008        **   (-0.000564, -0.0001291)
  events_T...giving+2    0.001287   0.001931      0.624               (-0.000992, 0.005448)
  events_Veterans Day    0.003422   0.004063      0.638               (-0.0008769, 0.01164)
  events_V...ns Day-1    0.001389   0.002025      0.618              (-0.0009361, 0.006219)
  events_V...ns Day-2  -0.0006708  0.0002258      0.016         *   (-0.001226, -0.0003203)
  events_V...ns Day+1      0.0055   0.005712      0.552                (-0.000859, 0.01768)
  events_V...ns Day+2  -0.0005547  0.0002121      0.020         *   (-0.001037, -0.0002418)
        str_dow_2-Tue    -0.01558    0.00341     <2e-16       ***     (-0.02267, -0.009056)
        str_dow_3-Wed   -0.008485   0.001448     <2e-16       ***      (-0.01152, -0.00585)
        str_dow_4-Thu    -0.01323   0.002289     <2e-16       ***     (-0.01759, -0.009112)
        str_dow_5-Fri   -0.008634   0.002869     <2e-16       ***       (-0.015, -0.002985)
        str_dow_6-Sat    0.005599   0.004733      0.244                  (-0.00427, 0.0147)
        str_dow_7-Sun     0.01382   0.008306      0.094         .     (-0.0005145, 0.03152)
                  ct1      0.1133    0.01364     <2e-16       ***         (0.08863, 0.1411)
       is_weekend:ct1     0.09005    0.02733     <2e-16       ***         (0.03949, 0.1494)
    str_dow_2-Tue:ct1    -0.08523    0.03007     <2e-16       ***       (-0.1437, -0.02681)
    str_dow_3-Wed:ct1  -0.0001746    0.01152      0.982                 (-0.02589, 0.02133)
    str_dow_4-Thu:ct1     -0.0571    0.01434     <2e-16       ***      (-0.08766, -0.03152)
    str_dow_5-Fri:ct1    -0.02598    0.02014      0.188                 (-0.06817, 0.01163)
    str_dow_6-Sat:ct1     0.04548    0.03482      0.180                  (-0.02331, 0.1115)
    str_dow_7-Sun:ct1     0.04457    0.05308      0.412                   (-0.04927, 0.152)
  ct1:sin1_tow_weekly     -0.1595    0.02545     <2e-16       ***        (-0.2133, -0.1086)
  ct1:cos1_tow_weekly      0.2312     0.0564     <2e-16       ***           (0.1335, 0.345)
  ct1:sin2_tow_weekly    -0.08241    0.03245      0.006        **       (-0.1511, -0.02678)
  ct1:cos2_tow_weekly      0.1082    0.05161      0.040         *          (0.01133, 0.208)
      sin1_tow_weekly    -0.03871   0.006369     <2e-16       ***       (-0.0516, -0.02609)
      cos1_tow_weekly     0.04575    0.01054     <2e-16       ***         (0.0279, 0.06659)
      sin2_tow_weekly    -0.01896   0.007285      0.004        **     (-0.03413, -0.005825)
      cos2_tow_weekly     0.01587   0.009883      0.102                 (-0.00312, 0.03488)
      sin3_tow_weekly   -0.006222   0.007811      0.436                (-0.02204, 0.008553)
      cos3_tow_weekly     0.03116    0.02094      0.144                 (-0.00962, 0.06928)
      sin4_tow_weekly    0.006222   0.007811      0.436                (-0.008553, 0.02204)
      cos4_tow_weekly     0.03116    0.02094      0.144                 (-0.00962, 0.06928)
   sin1_toq_quarterly  -0.0008779    0.02149      0.964                 (-0.04357, 0.04144)
   cos1_toq_quarterly    -0.01756     0.0222      0.448                 (-0.05844, 0.02542)
   sin2_toq_quarterly    -0.03217    0.02084      0.120                (-0.07517, 0.005218)
   cos2_toq_quarterly     0.01676    0.02183      0.432                  (-0.0251, 0.05949)
   sin3_toq_quarterly   -0.005791    0.01927      0.748                   (-0.04343, 0.032)
   cos3_toq_quarterly   -0.007139    0.02289      0.738                 (-0.05082, 0.03689)
   sin4_toq_quarterly   -0.004574    0.02212      0.830                 (-0.04553, 0.04431)
   cos4_toq_quarterly     0.02364    0.02129      0.274                 (-0.01809, 0.06758)
   sin5_toq_quarterly     0.01148    0.02365      0.622                 (-0.03579, 0.05784)
   cos5_toq_quarterly     0.03191    0.02302      0.156                 (-0.01291, 0.07795)
      sin1_ct1_yearly     0.01809    0.02135      0.374                 (-0.02103, 0.06225)
      cos1_ct1_yearly      0.1393    0.02396     <2e-16       ***         (0.09074, 0.1856)
      sin2_ct1_yearly     0.04222    0.02236      0.064         .        (0.00113, 0.09047)
      cos2_ct1_yearly     0.02117    0.02366      0.388                 (-0.02406, 0.06855)
      sin3_ct1_yearly     0.02121    0.02155      0.336                 (-0.01812, 0.06363)
      cos3_ct1_yearly    -0.01572    0.02384      0.488                 (-0.06457, 0.03148)
      sin4_ct1_yearly    -0.01478    0.02366      0.560                 (-0.05802, 0.03256)
      cos4_ct1_yearly    0.008635    0.01992      0.630                 (-0.03111, 0.04864)
      sin5_ct1_yearly   -0.008971    0.02085      0.680                 (-0.05072, 0.03267)
      cos5_ct1_yearly     0.02512    0.02332      0.278                 (-0.02056, 0.07096)
      sin6_ct1_yearly     0.02421    0.02249      0.286                  (-0.02138, 0.0675)
      cos6_ct1_yearly     0.01695    0.02143      0.450                 (-0.02297, 0.05724)
      sin7_ct1_yearly     0.01876    0.02071      0.346                  (-0.02244, 0.0617)
      cos7_ct1_yearly    -0.01169    0.02356      0.626                  (-0.0553, 0.03358)
      sin8_ct1_yearly   0.0009452    0.02163      0.962                 (-0.04415, 0.04326)
      cos8_ct1_yearly      -0.037    0.02101      0.078         .      (-0.07957, 0.002299)
      sin9_ct1_yearly    0.007784    0.01975      0.700                 (-0.03153, 0.04576)
      cos9_ct1_yearly    -0.01794    0.02463      0.440                 (-0.06577, 0.02958)
     sin10_ct1_yearly    0.008365    0.02246      0.714                 (-0.03226, 0.05086)
     cos10_ct1_yearly     0.02504    0.02187      0.252                  (-0.0185, 0.06596)
     sin11_ct1_yearly   -0.009925    0.02288      0.656                 (-0.05302, 0.03149)
     cos11_ct1_yearly     0.02143    0.02078      0.284                 (-0.02017, 0.06245)
     sin12_ct1_yearly   -0.003693    0.01923      0.828                 (-0.04128, 0.03361)
     cos12_ct1_yearly    -0.00725    0.02292      0.724                 (-0.05012, 0.03652)
     sin13_ct1_yearly     0.01691    0.02333      0.478                 (-0.02904, 0.06348)
     cos13_ct1_yearly    0.006987    0.02039      0.726                 (-0.03363, 0.04635)
     sin14_ct1_yearly      0.0148    0.01956      0.460                 (-0.02228, 0.05361)
     cos14_ct1_yearly     0.03283    0.02444      0.168                 (-0.01815, 0.07447)
     sin15_ct1_yearly     0.01077    0.02223      0.596                  (-0.03226, 0.0607)
     cos15_ct1_yearly     0.01311    0.02194      0.566                 (-0.03065, 0.05171)
Signif. Code: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Multiple R-squared: 0.008445,   Adjusted R-squared: 0.007605
F-statistic: 5.9931 on 5 and 6388 DF,   p-value: 7.809e-06
Model AIC: 1.032e+05,   model BIC: 1.032e+05

WARNING: the F-ratio and its p-value on regularized methods might be misleading, they are provided only for reference purposes.

In [41]:
result.backtest.df

             ds   actual   forecast  forecast_lower  forecast_upper
0    2003-12-01  4.77920   8.232051     -142.043604      158.507705
1    2003-12-02  4.77050   8.016040        5.996086       10.035993
2    2003-12-03  4.76550   8.110608        5.012914       11.208303
3    2003-12-04  4.77050   8.053784        5.685203       10.422365
4    2003-12-05  4.78700   8.093017      -19.155709       35.341742
...         ...      ...        ...             ...             ...
6390 2021-05-30  6.77660  20.061569     -108.534186      148.657323
6391 2021-05-31  6.76650  17.403677     -132.871977      167.679331
6392 2021-06-01  6.78380   7.124467        5.104514        9.144421
6393 2021-06-02      NaN   5.098391        2.000697        8.196085
6394 2021-06-03  6.78411   6.452223        4.083642        8.820805

[6395 rows x 5 columns]

In [40]:
result.forecast.df

             ds  actual   forecast  forecast_lower  forecast_upper
0    2003-12-01  4.7792   8.434334     -137.615114      154.483782
1    2003-12-02  4.7705   8.221028        5.927322       10.514735
2    2003-12-03  4.7655   8.310295        5.077554       11.543035
3    2003-12-04  4.7705   8.257330        5.654325       10.860335
4    2003-12-05  4.7870   8.295371      -18.182483       34.773225
...         ...     ...        ...             ...             ...
6755 2022-05-30     NaN  16.508481     -129.540967      162.557929
6756 2022-05-31     NaN   6.840650        4.546944        9.134357
6757 2022-06-01     NaN   5.120081        1.887340        8.352822
6758 2022-06-02     NaN   6.274590        3.671585        8.877595
6759 2022-06-03     NaN   7.065662      -19.412192       33.543515

[6760 rows x 5 columns]

In [ ]:
def collect_tune_and_predict(item,fred,n_ahead):
    param_grid =    {  
            'changepoint_prior_scale': [0.01, 0.1, 1.0, 5.0, 10.0],
            'seasonality_prior_scale': [0.01, 0.1, 1.0, 5.0, 10.0,],
                        }
    # Get Data
    data = fred.get_series_latest_release(item)
    data = pd.DataFrame(data)
    data.columns = ["y"]
    data['ds'] = data.index
    data = data.dropna()

    # Tune
    all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]
    rmses = [] 
    # Use cross validation to evaluate all parameters
    latest_date = data.tail(1).iloc[0]['ds']
    cutoffs = [ subtract_one_month( latest_date ) ]
    for params in all_params:
        m = Prophet(**params).fit(data)  # Fit model with given params
        df_cv = cross_validation(m, cutoffs=cutoffs, horizon='30 days', parallel="processes")
        df_p = performance_metrics(df_cv, rolling_window=1)
        rmses.append(df_p['rmse'].values[0])

    # Rolling windows
    # Find the best parameters
    tuning_results = pd.DataFrame(all_params)
    tuning_results['rmse'] = rmses
    # Python
    best_params = all_params[np.argmin(rmses)]

    # Python
    m = Prophet(**best_params)
    m.fit(data)
    
    best_params['rmse'] = min( rmses )
    print(best_params)
    # Python
    future = m.make_future_dataframe(periods=n_ahead)
    forecast = m.predict(future)
    # SMA
    sma = pd.DataFrame(data = { 
                                'ds' : data['ds'], 
                                'SMA_50' : data['y'].rolling(window=50,min_periods=1).mean(), 
                                'SMA_100' : data['y'].rolling(window=100,min_periods=1).mean(),
                                'SMA_200' : data['y'].rolling(window=200,min_periods=1).mean()
    })
    # Join SMA
    forecast = pd.merge(forecast,sma,on='ds',how='left')
    fig1 = plot_(m,forecast)
    a = add_changepoints_to_plot(fig1.gca(), m, forecast)
    # Python
    fig2 = m.plot_components(forecast)

    # Latest 365
    future = m.make_future_dataframe(periods=30)
    forecast = m.predict(future)
    forecast = pd.merge(forecast,sma,on='ds',how='left')
    forecast = forecast[forecast['ds'] >= subtract_one_year( datetime.today() )]
    m.history = m.history[m.history['ds'] >= subtract_one_year( datetime.today() )]
    fig3 = plot_(m,forecast)
    return( { 'fig1' : fig1, 'fig2' : fig2, 'fig3': fig3})

In [ ]:
def plot_(
    m, fcst, ax=None, uncertainty=True, plot_cap=True, xlabel='ds', ylabel='y',
    figsize=(10, 6), include_legend=False
):
    """Plot the Prophet forecast.
    Parameters
    ----------
    m: Prophet model.
    fcst: pd.DataFrame output of m.predict.
    ax: Optional matplotlib axes on which to plot.
    uncertainty: Optional boolean to plot uncertainty intervals, which will
        only be done if m.uncertainty_samples > 0.
    plot_cap: Optional boolean indicating if the capacity should be shown
        in the figure, if available.
    xlabel: Optional label name on X-axis
    ylabel: Optional label name on Y-axis
    figsize: Optional tuple width, height in inches.
    include_legend: Optional boolean to add legend to the plot.
    Returns
    -------
    A matplotlib figure.
    """
    if ax is None:
        fig = plt.figure(facecolor='w', figsize=figsize)
        ax = fig.add_subplot(111)
    else:
        fig = ax.get_figure()
    fcst_t = fcst['ds'].dt.to_pydatetime()
    ax.plot(m.history['ds'].dt.to_pydatetime(), m.history['y'], 'k.',
            label='Observed data points')
    ax.plot(fcst_t, fcst['yhat'], ls='-', c='#0072B2', label='Forecast')
    if 'cap' in fcst and plot_cap:
        ax.plot(fcst_t, fcst['cap'], ls='--', c='k', label='Maximum capacity')
    if m.logistic_floor and 'floor' in fcst and plot_cap:
        ax.plot(fcst_t, fcst['floor'], ls='--', c='k', label='Minimum capacity')
    if uncertainty and m.uncertainty_samples:
        ax.fill_between(fcst_t, fcst['yhat_lower'], fcst['yhat_upper'],
                        color='#0072B2', alpha=0.2, label='Uncertainty interval')
    # Specify formatting to workaround matplotlib issue #12925
    locator = AutoDateLocator(interval_multiples=False)
    formatter = AutoDateFormatter(locator)
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)
    ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    # SMA
    ax.plot(fcst['ds'],fcst['SMA_50'] )
    ax.plot(fcst['ds'],fcst['SMA_100'] )
    ax.plot(fcst['ds'],fcst['SMA_200'] )
    if include_legend:
        ax.legend()
    fig.tight_layout()
    return fig